### PR TITLE
Use saved password with no prompt if silent_connection is on

### PR DESCRIPTION
**Pull request by selvanair**
The behaviour is unchanged if silent_connection is not enabled either on command line or
in the GUI settings.
See also #185 

Signed-off-by: Selva Nair <selva.nair@gmail.com>

### CODE REVIEW

**Comment by chipitsine** [comment]
Can we merge it?

**Comment by selvanair** [comment]
@chipitsine: There has been some user feedback suggesting this should not be coupled to 'silent_connection' and a separate checkbox that allows to skip this dialog would be more friendly (see #193). E.g.,  a check box on the password dialog window that says don't show this dialog again.

If this is useful as is, I'm open to lazy ACK it. It cant hurt anyway.

**Comment by chipitsine** [comment]
@selvanair , personally I like a bit different way of "silent" reconnection.

I observed it on SoftEtherVPN. If password is saved, so timer is on about 5 sec which let you to interrupt reconnect if you want. If you do not interrupt reconnection, it reconnects with no user interaction.


your way is also good, I think, so, I'd merge it

**Comment by chipitsine** [comment]
almost-silent


something like that (it was another kind of reconnection, due to network error, but idea is the same)

**Comment by chipitsine** [comment]
I just meant UI, not reconnection.
same UI with moving green line can be used for "silent" connections. i.e. it connect in several second unless user wishes to interrupt it

**Comment by selvanair** [comment]
@chipitsine Based on your remarks, I propose the "auto-submit saved credentials if silent" behaviour of this PR coupled with "always submit within a few seconds unless the user interacts". A patch that implements this is in a private branch [here](https://github.com/selvanair/openvpn-gui/tree/no-auth-prompt-v2)

A progress bar looks odd in such a dialog, so it just displays a message saying "Continuing with saved data in 5 seconds.." User can interrupt and submit right away (click OK), or edit any of the fields in which case the scheduled submit is cancelled. 

If this looks promising, please test.

**Comment by chipitsine** [comment]
@selvanair - I'm afraid, I will not provide you any relevant feedback, I will ask our users instead...

as for me, it is great, however, couple of notices

1. "Continuing with prefilled..." should not be red. red means an error, i.e. "pay attention to me".

2. Some interaction with user should be nice, if not a green line, so maybe countdown timer ? 5 sec ... 4 sec ... 3 sec... ? If something is going on, user will treat it as "ok, it is going on, no interaction from me required"

**Comment by chipitsine** [comment]
@selvanair , can you, please enable App Veyor ? it keeps artifacts across builds, that simplifies "here's brand new openvpn-gui, please test" scenario.

I merged your commits https://ci.appveyor.com/project/chipitsine/openvpn-gui-nhep8

**Comment by chipitsine** [comment]
also, I would change

"Continuing with prefilled data in %u seconds..."

with

"Connect automatically in %u sec."

**Comment by selvanair** [comment]
@chipitsine : Thanks for the feedback. Will address all in the next version.

**Comment by selvanair** [comment]
Updated:
When saved username and password are available:
(i) If silent_connection is on bypass auth-user-pass dialog
(ii) Else auto submit after a brief delay unless the user interrupts
(iii) Show a message "Connecting automatically after <time-remaining> seconds"

**Comment by chipitsine** [comment]
I tested it. much better UX, let's merge it

**Pull request merged**
