### PR TITLE
Update openvpn-gui-res-ua.rc

### PR DESCRIPTION
**Pull request by toxi22**

### CODE REVIEW

**Comment by selvanair** [comment]
This may be much easier handled as a comment on PR 167.

**Comment by zhovner** [comment]
Finished Ukrainian translation with missed strings selvanair#7

**Comment by selvanair** [comment]
> Finished Ukrainian translation with missed strings [selvanair#7](https://github.com/selvanair/openvpn-gui/pull/7)

@zhovner Thanks. Could you please target the PR to here, i.e., OpenVPN/openvpn-gui:master ?

**Comment by zhovner** [comment]
@selvanair done

**Comment by selvanair** [comment]
> @selvanair done #361
If you use your resource-strings branch for this as you did earlier when you targetted my fork, it would be better. It will show up as two commits but that's okay. Otherwise this is going to conflict as soon as we merge 360. 

Or wait for a review in case any changes are needed.

**Comment by toxi22** [comment]
This version is better: https://github.com/OpenVPN/openvpn-gui/pull/362

**Pull request closed without merging**
