### PR TITLE
Dynamic challenge response support

### PR DESCRIPTION
**Pull request by selvanair**
This is rebased to PR #86 so the first three commits are the same and may be ignored.

### CODE REVIEW

**Comment by cron2** [comment]
Hi,

On Sat, Oct 08, 2016 at 11:53:12PM -0700, Selva Nair wrote:
>   * Handle dynamic challenge/response

I have no idea what OpenVPN and the management interface will do here
(and my own test server to hand out challenges is still not done) - so
"feature-ACK" only.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by selvanair** [comment]
Rebased to master and replaced strtok_r by strtok  as the former is not in some versions of mingw. For our purposes strtok is good enough.

**Comment by mattock** [comment]
If nobody can provide a review, I say we merged this with lazy-ACK. We definitely want this in the openvpn-gui.exe version bundled with OpenVPN 2.4_rc1 installers.

**Comment by cron2** [comment]
Hi,

On Mon, Nov 21, 2016 at 06:17:44AM -0800, Samuli Seppänen wrote:
> If nobody can provide a review, I say we merged this with lazy-ACK. We definitely want this in the openvpn-gui.exe version bundled with OpenVPN 2.4_rc1 installers.

Feature-ACK :-) - can't comment on the code (and still have not found time
to set up a test server with CR auth)

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment]
When the _selvanair/dynamic-cr_ branch is merged, _selvanair/pkcs11-pin-v3_ will no longer apply cleanly due to a large number of merge conlicts in openvpn.c and options.h. Some of the conflicts were not trivial enough for me to fix, without understanding the code.

I will produce and installer which includes dynamic-cr and dpi-aware branches, as those seem to work fine together.

**Comment by selvanair** [comment]
I included the dynamic-cr commit in the pkcs11-pin-v3 branch (because of dependencies), so that would explain the conflicts. If you skip the dynamic-cr PR and apply the pkcs11-pn-v3 PR it will work, I think.

Anyway, let's get some feedback on the installers you made. pkcs11 pin part has been tested by one user at least.

**Comment by selvanair** [comment]
commit included in PR 91 (merged). Closing.

**Pull request closed without merging**
