### PR TITLE
Adding static-challenge support

### PR DESCRIPTION
**Pull request by soarqin**
I also copied all usable translations in dialog resources, there is only 1 new string for translation: "Challenge"

### CODE REVIEW

**Comment by soarqin** [comment]
okay, I will fix these asap

**Comment by soarqin** [comment]
@selvanair For TCHAR type, I just follow what GetDlgItemTextUtf8() does in misc.c, which treats LPTSTR as LPWSTR, so I will also fix this function.

**Comment by selvanair** [comment]
Hmm.. If there are many such places where TCHAR is assumed to be WCHAR, we could just leave it as is and can do a patch if required later? Samuli may know whether anyone compiles this without -D_UNICODE

@samuli  can we just put a preprocessor check UNICODE and _UNICODE are defined and bail out otherwise?

**Comment by soarqin** [comment]
re-commited, supported ECHO field, moved base64 implementation to win32 cryptoapi (I do think we could also use OpenSSL if don't want crypt32.lib)

**Comment by selvanair** [comment]
Looks good and works as expected. ACK.
Closes [#525](https://community.openvpn.net/openvpn/ticket/525)

Note: The max length of the static-challenge text that displays correctly is about 40 chars depending on word wrap. This should be adequate for most users?

**Comment by soarqin** [comment]
40 chars are enough in most scene, challenge system is usually for MFA-like auth which sends very simple words.

**Comment by selvanair** [comment]
Good enough for me: I use "Enter google authenticator code" :-)

**Comment by mattock** [comment]
@selvanair: I don't know of anyone building openvpn-gui without unicode support. We probably have no way to know that except by requiring unicode.

Anyways, based on my smoketesting ("builds and other functionality does not seem to break") and Selva's more extensive tests I'll merge this.

**Pull request merged**
