### PR TITLE
AppVeyor: stick to mingw64-%ARCH%-gcc-core-5.4.0-3

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by chipitsine** [comment]
I could not yet figured out why cross build is treated as native build (and so executable is checked)

**Comment by chipitsine** [comment]
and, great! we have artifacts available

https://ci.appveyor.com/project/mattock/openvpn-gui/build/cygwin-5/job/v487wllh136p6vca/artifacts

**Comment by mattock** [comment]
Really nice to get openvpn-gui.exe out from each PR! This PR looks reasonable, so merging it.

**Comment by chipitsine** [comment]
cygwin keeps 3 previous versions.
5.4.0-3 will not be available soon :-)

**Pull request merged**
