### PR TITLE
WIP: Use RTL layout for Farsi

### PR DESCRIPTION
**Pull request by selvanair**
This requires feedback from Persian language users

Signed-off-by: Selva Nair <selva.nair@gmail.com>

### CODE REVIEW

**Comment by lstipakov** [comment]
Not too much into Farsi, but looks indeed RTL.

Näyttökuva 2022-11-28 100000

**Review by lstipakov — APPROVED** [review]
Let's wait for Farsi speaker for confirmation.

**Comment by selvanair** [comment]
Added a commit to fix some bidirectional text in "About"
Before: 
about-b

Incorrect character ordering of trailing ">" and "/"  leads to "<Copyright ..." and "/https://..."

After:
about-a

The fix uses explicit LRE markers. If there is a better way, please suggest.

**Comment by selvanair** [comment]
"WIP" removed from commit message and force-pushed. No code changes.

**Pull request merged**
