### PR TITLE
added cppcheck, openssl-1.0.1r

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by selvanair** [comment]
This looks good, but I am not sure of how the irc notification works: would it not be nuisance with travis builds on forks sending notification to the irc channel? Or is there an option to make forks not send such notifications? If not, sticking with the default email notifications may be better.

**Comment by chipitsine** [comment]
ok, can you commit everything except irc notifications ?

**Comment by selvanair** [comment]
Looks good to me. ACK.

**Comment by mattock** [comment]
@selvanair : I think Travis CI (build failure) notifications on #openvpn-windows could prove useful. Nothing tends to happen on that channel anyways. That said, I'll ask about this on the channel first.

**Comment by selvanair** [comment]
@mattock I was only concerned with notifications from forks that have travis build enabled (mine is one). If that extra noise is tolerable, let's go for it.

**Pull request merged**
