### PR TITLE
Show assigned ipv6 address in balloon and tray popup

### PR DESCRIPTION
**Pull request by selvanair**
Signed-off-by: Selva Nair <selva.nair@gmail.com>

### CODE REVIEW

**Comment by cron2** [comment]
Hi,

On Sat, Jan 27, 2018 at 11:53:49PM +0000, Selva Nair wrote:
> Signed-off-by: Selva Nair <selva.nair@gmail.com>
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OpenVPN/openvpn-gui/pull/210
> 
> -- Commit Summary --
> 
>   * Show assigned ipv6 address in balloon and tray popup

Line 259 looks a bit funny

    if (strcmp(state, "CONNECTED") ==0)

with one space left of the "==" and no space right of it - but that's
just whitespace.


Besides that, it looks good to me.  And useful at that :-) - so, ACK.

gert


-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment]
Indeed. Fixed the missing space and pushed.
Thanks for the review.

**Comment by selvanair** [comment]
@mattock: Is there any advantage of continuing to use merge commits for PRs on github? Shall we start using the rebase-and-merge option? Assuming it works the way it should..

**Comment by mattock** [comment]
@selvanair oh, I did not know we have a [rebase-and-merge option](https://github.com/blog/2243-rebase-and-merge-pull-requests) until now :smile:. I do prefer having a cleaner history without merge commits. The only loss would be a lack of link between the PR and the commits, but that's not a big deal imho.

So let's give rebase-and-merge a go.

**Pull request merged**
