### PR TITLE
Fix translation

### PR DESCRIPTION
**Pull request by ikreb7**

### CODE REVIEW

**Comment by cron2** [comment]
Hi,

On Tue, Mar 24, 2020 at 02:51:31PM -0700, ikreb7 wrote:
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OpenVPN/openvpn-gui/pull/345
> 
> -- Commit Summary --
> 
>   * fix typo

I have no very strong opinion on "Logdatei" vs. "Logfile", but if you
change it for "log_viewer", please do also change it for the adjacent
line, "--append_string".

"--log_dir" already uses "Logdatei", so either make it "Logdatei"
in all places, or "Logfile" everywhere...

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by ikreb7** [comment]
I hope it is consistent now.

**Comment by mattock** [comment]
And there is a merge conflict now. This probably won't make it to OpenVPN 2.5_beta1, but that is not too bad as the subsequent release will happen quite soon after.

**Comment by selvanair** [comment]
Closing this as changes proposed here have already been made in some form or other by PR #285

**Pull request closed without merging**
