### PR TITLE
Update CHANGES.rst

### PR DESCRIPTION
**Pull request by selvanair**
This has been left uncared for since 2015. 
Generated by manually editing the commit-log with a heavy hand -- I've tried to include a line on all significant changes, hope I did not miss any important ones.

### CODE REVIEW

**Comment by schwabe** [comment]
wow that looks like a lot of effort!

**Comment by selvanair** [comment]
> wow that looks like a lot of effort! 

Yeah, painful, but from now we'll keep this current, hopefully :).

> I would approve this but I seem not have permission to do so... 

I'll take a that as an ACK... I was under the impression that anyone can approve PRs on this repo. Probably moderation is enabled by @mattock --- I do not have access to those settings.

**Comment by cron2** [comment]
For some reasons I do not fully understand (maybe inheritance) I do have full "click on everything" access, and I think it makes sense that @selvanair has full admin access to this repo - so, clickediclick, now you can wreck everything with a few mouse clicks :-)

@plaisthos usually we just send "LGTM" or "ACK" here and Lev or Selva will then do the merge...

**Comment by selvanair** [comment]
> For some reasons I do not fully understand (maybe inheritance) I do have full "click on everything" access, and I think it makes sense that @selvanair has full admin access to this repo - so, clickediclick, now you can wreck everything with a few mouse clicks :-)
>

Will have to take even more care from now on with my mouse-clicks..
 
> @plaisthos usually we just send "LGTM" or "ACK" here and Lev or Selva will then do the merge...

I think its okay to allow anyone to approve as we treat that only as an opinion and not just blindly accept an "approve" from anyone as a signal to merge.
Just checked the moderation options: code review limit is not imposed, anyone should be able to approve PRs. It could be imposed at the org level though -- not sure how that inheritance works.

**Comment by cron2** [comment]
Hi,

On Wed, Dec 07, 2022 at 01:47:23PM -0800, Selva Nair wrote:
> > For some reasons I do not fully understand (maybe inheritance) I do have full "click on everything" access, and I think it makes sense that @selvanair has full admin access to this repo - so, clickediclick, now you can wreck everything with a few mouse clicks :-)
> 
> Will have to take even more care from now on with my mouse-clicks..

I know that feeling :-) - so if you feel uncomfortable, just let me
know what level of access you want.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Pull request merged**
