### PR TITLE
Improve many Dutch translations

### PR DESCRIPTION
**Pull request by ffes**
This PR improves many Dutch texts.

### CODE REVIEW

**Comment by mattock** [comment]
Hi,

I asked a dutch speaker to review the changes.

**Comment by selvanair** [comment]
Good to see translation improvements..
Recent patches have introduced a number of strings with only the english version in openvpn-gui-res-en.rc filled in. Should we copy these into all language files so that they get noticed by translators?

Here is a list (for those marked [*], Portuguese is also already filled-in)

```
[*] IDS_MENU_IMPORT "Import file…"
    IDS_NFO_NO_CONFIGS "No readable connection profiles (config files) found"
    IDS_NFO_CONN_TIMEOUT "Connecting to management interface failed.\n" \
                         "View log file (%s) for more details."
    IDS_ERR_ACCESS_SERVICE_PIPE "Access to service pipe failed."
    IDS_ERR_WRITE_SERVICE_PIPE "Writing to service pipe failed."
    IDS_ERR_INSTALL_ISERVICE     """OpenVPNServiceInteractive"" is not installed.\n"
                                 "Tasks requiring administrative access may not work."
     IDS_ERR_NOTSTARTED_ISERVICE  """OpenVPNServiceInteractive"" is not started.\n"
                                 "Tasks requiring administrative access may not work."
    IDS_ERR_GET_PROFILE_DIR "Error getting User Profile Directory."
[*] IDS_ERR_IMPORT_EXISTS "A config named ""%s"" already exists."
[*] IDS_ERR_IMPORT_FAILED "Failed to import file. The following path could not be created.\n\n" \
                          "%s\n\nMake sure you have the right permissions."
[*] IDS_NFO_IMPORT_SUCCESS "File imported successfully."
```

**Comment by syzzer** [comment]
Translations look good to me.

Bedankt!

**Comment by ffes** [comment]
All the strings mentioned above, not just those with a [*], are missing in the Dutch translation.

I found [this tool](http://www.codeproject.com/Articles/7674/Resource-Comparer) and [this tool](http://www.codeproject.com/Articles/3711/RC-Localization-Tool-LocalizeRC) which could maybe help to locate the diffs between the various .rc files, but I haven't tried them yet.

**Comment by selvanair** [comment]
> All the strings mentioned above, not just those with a [*], are missing in the Dutch translation.

That is correct. The list was of recently added strings which are missing from most language files except English. The * refers to those present in Portuguese (before PR 31) and English but no other language files. 

Would you like to update the PR with those missing ones for Dutch? If not, we can merge this one for now and add those later.

**Comment by selvanair** [comment]
These changes are already useful, so merging as is. Feel free to submit another PR for the missing text strings.

**Pull request merged**
