### PR TITLE
Appveyor small improvements

### PR DESCRIPTION
**Pull request by Chocobo1**
* AppVeyor: add shebang
  Fix indention.
  Not sure if there is a reason to omit it...
* Readme: add AppVeyor badge
  So that you can navigate to the page and get the artifacts easily.

Page in action: https://github.com/Chocobo1/openvpn-gui/tree/appveyor#openvpn-gui

There are 2 minor things beside this PR:
1. `appveyor.yml` can actually be renamed to `.appveyor.yml`, if you want coherent naming with `.travis.yml`.
2. The artifact should be able to be compressed to zip (example: https://github.com/RPCS3/rpcs3/blob/master/appveyor.yml#L38) or to 7z (with custom command) if you want...

### CODE REVIEW

**Comment by chipitsine** [comment]
appveyor.sh is a crap, I was going to move all variables into appveyor.yml and remove that file.

**Comment by chipitsine** [comment]
actually "build passed" usually means something like "tests passed". and, building on AppVeyor allows to run openvpn-gui.exe and perform either smoke testing of gui (like running "openvpn-gui.exe --help" and pressing "Ok" button using AutoIT or Powershell, or run some unit tests), currently is not testing, just "let us see whether it builds or not"

**Comment by mattock** [comment]
@Chocobo1 there are several whitespace changes in this PR (see https://github.com/OpenVPN/openvpn-gui/pull/145/files). Once those are fixed I would be willing to merge this. That said, it would be nice to see which CI the builds are passing for. [Right now](https://github.com/Chocobo1/openvpn-gui/tree/appveyor#openvpn-gui) there are just two anonymous "Build passing" badges (Travis + Appveyor); one has to hover on top of them to see what service they refer to.

@chipitsine how far are your in migrating to .appveyor.yml? This PR is trivial enough to merge even if only temporily.

**Comment by chipitsine** [comment]
Let us merge this PR

**Comment by chipitsine** [comment]
As for "build passing", both travis and appveyor badges are well known, I beleive they are enough

**Comment by Chocobo1** [comment]
>@Chocobo1 there are several whitespace changes in this PR (see https://github.com/OpenVPN/openvpn-gui/pull/145/files). Once those are fixed I would be willing to merge this. 

OK, done.

**Comment by mattock** [comment]
Merging, thanks to all!

**Pull request merged**
