### PR TITLE
pkcs11 pin prompt

### PR DESCRIPTION
**Pull request by selvanair**
Support pkcs11 token insertion request and token pin input

(This is built on top of PR 87, so ignore the first commit)

### CODE REVIEW

**Comment by selvanair** [comment]
@valdikSS: could you please give a review of this? This one and dynamic CR support are two useful features to have in the GUI.

**Comment by selvanair** [comment]
PKCS11 prompt function tested by @bjoernv on [Trac 740#16](https://community.openvpn.net/openvpn/ticket/740#comment:15)

**Comment by selvanair** [comment]
@mattock I think we may have to use lazy ACK on this to get this into 2.4-rc1 and hopefully some testing in the wild before 2.4. We can ignore PR 87 as that one is the same as the first commit here.

**Comment by mattock** [comment]
@selvanair : agreed. The endless loop thing was fixed at the OpenVPN side, right?

**Comment by selvanair** [comment]
No, the endless loop is not fixed. It seems no one understands that part of the code in OpenVPN -- at least I did not get any response. Anyway it apparently shows up only if the token is removed mind-way through the password dialog (I haven't reproduced it) and is reportedly seen in command line usage as well. Its not a runaway loop, openvpn just re-prompts the user to insert the token even if the user presses cancel.

**Comment by cron2** [comment]
Hi,

On Tue, Nov 29, 2016 at 10:31:35PM -0800, Samuli Seppänen wrote:
> @selvanair : agreed. The endless loop thing was fixed at the OpenVPN side, right?

No, that was another endless loop (much easier to understand, just our
own code, no pkcs11-helper involved).

Maybe @syzzer has some ideas, or @jjk.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by chipitsine** [comment]
2016-11-30 10:28 GMT+03:00 Gert Doering <notifications@github.com>:

> Hi,
>
> On Tue, Nov 29, 2016 at 10:31:35PM -0800, Samuli Seppänen wrote:
> > @selvanair : agreed. The endless loop thing was fixed at the OpenVPN
> side, right?
>
> No, that was another endless loop (much easier to understand, just our
> own code, no pkcs11-helper involved).
>

can we involve some static analyzer (like clang or coverity) to detect
endless loops ?

or "token was removed" is rather impossible to detect ?

**Comment by cron2** [comment]
Hi,

On Tue, Nov 29, 2016 at 11:57:31PM -0800, Ilya Shipitsin wrote:
> 2016-11-30 10:28 GMT+03:00 Gert Doering <notifications@github.com>:
> 
> can we involve some static analyzer (like clang or coverity) to detect
> endless loops ?

"brains" is more helpful here :-) - because that loop is usually *not*
endless.  

It's likely some sort of retry-on-failure loop that does not handle 
certain error conditions right.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by ValdikSS** [comment]
What endless loop are you talking about? I have some problems with pkcs11 in OpenVPN in Linux, it deadlocks sometime, so I need to run it with strace, that way the probability of deadlock is much less.

**Comment by selvanair** [comment]
On Wed, Nov 30, 2016 at 3:26 AM, ValdikSS <notifications@github.com> wrote:

> What endless loop are you talking about? I have some problems with pkcs11
> in OpenVPN in Linux, it deadlocks sometime, so I need to run it with
> strace, that way the probability of deadlock is much less.
>
Its not an endless loop like a runaway train. Its what one would expect
from something like --auth-retry interact except that sending "cancel"
instead of "OK" to the token insertion request does not make the process
exit. Instead it just goes back to something like "insert the token now"
like a car navigation system repeatedly asking you to take a u-turn.

Again this does not happen unless the token is removed mid-way through a
password prompt.

See Trac: #740 comment 15:
https://community.openvpn.net/openvpn/ticket/740#comment:15

**Comment by mattock** [comment]
Merging as agreed in today's community meeting. What remains to be fixed cannot be fixed on the OpenVPN-GUI side.

**Pull request merged**
