### PR TITLE
Support sending commands to a running instance of the GUI

### PR DESCRIPTION
**Pull request by selvanair**
A test executable is [here](https://github.com/selvanair/openvpn-gui/releases/tag/v11_testing1)

There are a number of commits here --- the main commit (df07beb) does what the heading says. Commit 2467640 adds as button to the menu for reconnect (a convenience as the button in the status window is hard to reach). This one is now referred to by the rest of the commits so leaving it in here instead of opening a separate PR for it.

All other commits are improvements based on feedback and comments by those who tested an earlier version.
 
- New option --command <action> <params> to send commands to a running instance of openvpn-gui.exe

  Supported actions are
      connect, disconnect, reconnect
  each of which takes the name of the config (with or without the extension .ovpn) as a parameter;
      disconnect_all, exit
  which take no parameter and
      silent_connection
  which takes an optional parameter = 0 or 1 (1 is the default)

  Examples: with the gui running, start a new instance as

  `openvpn-gui.exe --command disconnect myvpn` : ask running instance to disconnect myvpn if connected
  `openvpn-gui.exe --command status myvpn`    : ask running instance to show the status window for myvpn if available
 `openvpn-gui.exe --command disconnect_all`   : ask running instance to disconnect all active connections

- The second instance exits after issuing a SendMessage to the already running instance. If no action is specified, the running instance is notified to show a balloon to alert the user

- These messages may also be sent from scripts as COPYDATA messages with the wData element specifying the action to execute and lpData  a pointer to the parameter. The dwData param must be one of WM_OVPN_xxx with xxx = START, STOP, RESTART, STOPALL, EXIT or SILENT. See main.h for their values.

v2: Bug fixes based on test reports from larson0815 here: selvanair#5
and cron410 here: #104

Signed-off-by: Selva Nair <selva.nair@gmail.com>

### CODE REVIEW

**Comment by selvanair** [comment]
Ugh.. it seems github's displays commits ordered by date (instead of topology of the tree). What I referred to as #2 is #1 now..

**Comment by selvanair** [comment]
Any volunteers to do some more tests on this? The appveyor build has a cached executable:
 https://ci.appveyor.com/project/mattock/openvpn-gui/build/cygwin-85/job/eotpj5t3jo2g2q88/artifacts

We would like to get this into the next release.

**Comment by selvanair** [comment]
@mattock: shall we merge this in time for the release with a lazy ack? (I've rebased it to master)..

**Comment by selvanair** [comment]
I plan to merge this in time for the release unless some one objects soon enough..

**Comment by mattock** [comment]
@selvanair sorry missed this one. But I would not have had any objections about going with lazy-ACK.

**Pull request merged**
