### PR TITLE
Update About page

### PR DESCRIPTION
**Pull request by mattock**
Proposal based  on discussion in PR https://github.com/OpenVPN/openvpn-gui/pull/76

Right now the text might overflow, but I'll fix that after we've agreed upon the content.

### CODE REVIEW

**Comment by mattock** [comment]
While Git logs indicate that many of Heiko's commits were made at Sophos, (a German company) [there is no corporate copyright in Germany](https://en.wikipedia.org/wiki/Copyright_law_of_Germany#Transfer). So copyrights for all of Heiko's changes belong to him afaict. I will ask him just in case. I chose  "(C) 2012-2016 OpenVPN GUI contributors" as 2012 was when Alon made a few commits - prior to that all commits in Git were Heiko's.

**Comment by selvanair** [comment]
Looks ok to me except that the term "OpenVPN GUI contributors" is vague, which is fine, but the link provided (openvpn.net) doesn't help in clarifying it. That said, I'm not informed enough to make any better suggestions. @cron2 may have some thoughts?

**Comment by cron2** [comment]
Hi,

On Thu, Oct 13, 2016 at 07:47:51AM -0700, Selva Nair wrote:
> Looks ok to me except that the term "OpenVPN GUI contributors" is vague, which is fine, but the link provided (openvpn.net) doesn't help in clarifying it. That said, I'm not informed enough to make any better suggestions. @cron2 may have some thoughts?

No idea, tbh.  Never did much on the GUI side, except scratch my head
at the windows code in there :-) - mattock might know... and @d12fk has
resurfaced again :-)

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by selvanair** [comment]
In the absence of any better suggestions, I guess we go with this. We have to check how it displays and also update all language files.

**Comment by mattock** [comment]
Contents of this PR were accidentally destroyed - please review https://github.com/OpenVPN/openvpn-gui/pull/89 instead. I believe it is ready for merging.

**Pull request closed without merging**
