### PR TITLE
Registry and admin

### PR DESCRIPTION
**Pull request by selvanair**
First two commits address issues discussed in 
http://article.gmane.org/gmane.network.openvpn.devel/11051
http://article.gmane.org/gmane.network.openvpn.devel/11060

The third commit fixes the path to notepad.exe

### CODE REVIEW

**Comment by mattock** [comment]
I will build test installers with this patchset and do some testing.

**Comment by mattock** [comment]
Test installers are available here:

* http://build.openvpn.net/downloads/temp/openvpn-install-2.3_guipr13-I601-i686.exe
* http://build.openvpn.net/downloads/temp/openvpn-install-2.3_guipr13-I601-x86_64.exe

I will do some testing later today on a Windows 7 laptop.

**Comment by mattock** [comment]
Everyone ok with merging this PR?

**Comment by selvanair** [comment]
For a cleaner history, may I rebase and force push the topic branch before you merge?

**Comment by mattock** [comment]
Feel free to rebase and force push.

**Comment by selvanair** [comment]
Squashed the the two fixups and rebased master. No code changes.

**Comment by mattock** [comment]
Merging this PR as there have been no complaints/concerns, and testing shows the code works as expected.

**Pull request merged**
