### PR TITLE
Update Ukrainian localization

### PR DESCRIPTION
**Pull request by VasyaPRO**

### CODE REVIEW

**Comment by ValdikSS** [comment]
I sent email to the person who made earlier Ukrainian translations.
@zhovner, please check it too.

**Comment by zhovner** [comment]
Do not merge until we check with others.

**Comment by ki84** [comment]
95 - З'єднати знову /  повторно - never heard this verb with devices, or even animals
96 - Згорнути 
102 - Зміна пароля приватного ключа"    / can't be used, because long texts in taskbar appeared as shit.

130 - Ручні налаштування проксі / can clearly understand why do you offer yours than mine
142 - Загальні налаштування / can clearly understand why do you offer yours than mine


154 - Додати, а не перезаписувати журнал / дописати - unclear with this verb
157 - Відображати спливаюче вікно під час:   / показувати - smth unusual as for me, who lived in Ukraine until now.
159 - / mine appears better to look, as its shorter

166 - Додаткові / yours is not often used with devices in Ukraine. 

196 - Про программне забеспечення OPENVPN / in this window it appears in Header or in Top of screen, it is enough to write a lot of text.

Від'єднати
247 - / Показати is not used often, as I can remember now atm.
250-258 / what's wrong with сервiс?

298-299 / поточний стан or стан is not used for devices in Ukraine, as I can remember.

332 / you wrote Ви в даний момент з'єднані, I can not use Ви for messaging about computer.  Looks really strange.


other words is not looking bad, but have to look later.


verbs with у in the endings looking terrible. It is not used often in this cases.

**Comment by selvanair** [comment]
@zhovner : Any progress on reviewing this?.

**Comment by mattock** [comment]
Any progress here? The next OpenVPN release, 2.4.5, is due 25th Jan (in two days) and I'd like to bundle a version of openvpn-gui that has an updated Ukrainian localization.

**Comment by zhovner** [comment]
The main issue with ukrainian localization, is that almost nobody uses it in common technical systems and there are no well-established speech forms for many technical terms. So use current version until we found Ukrainian Ph.D. in Linguistics.

**Comment by mattock** [comment]
@zhovner this translation adds some missing strings and getting those merged would be good.

**Comment by mattock** [comment]
Any progress here? At minimum getting the missing string translated would be good.

**Comment by mattock** [comment]
@ValdikSS excellent!

**Comment by zhovner** [comment]
How to correctly add missed strings from EN resource file to UA? I see that some strings is missed in UA file but I don't know how find which one.

**Comment by selvanair** [comment]
Some have found the [this tool](https://www.codeproject.com/Articles/7674/Resource-Comparer) useful in the past. Its not perfect but helps  --- like multi-line descriptions are parsed as a missing string, so the help message will lead to many false reports of missing strings etc.

Also note that the help message defined in IDS_NFO_USAGE has recently got some extra stuff like description of the --command option.

**Comment by mattock** [comment]
If you can wrap this up soonish these changes could be released in the OpenVPN 2.5.0 installer. OpenVPN 2.5_beta1 release process has started today.

**Comment by ValdikSS** [comment]
@mattock can you help with merging this request with current English resource strings? As far as I see, there are missing strings here.

**Comment by lstipakov** [comment]
This has unresolved conflicts.

**Comment by selvanair** [comment]
The consensus based on comments (@ki84 in 2017, @zhovner in 2018) seems to be to just use the current version and ignore the changes proposed here until better alternatives can be found.

I can insert all missing strings and issue a PR if that helps.

**Comment by selvanair** [comment]
See PR #360

**Comment by mattock** [comment]
@selvanair so fix merge conflicts here and then merge this (#167) and your PR (#360) and we're done, Correct?

**Comment by selvanair** [comment]
We have to merge 360 first and then fix merge conflicts here. 360 has been a major pain to put together (done manually) so I don't want to create merge conflicts in it.

Also, this one needs more than conflict resolution. Reviews have only questioned the translation proposed here. Someone will have to take good stuff from this and make a new PR. Before that, if you don't notice anything obviously wrong with 360, let's merge it first. I lightly tested it by going through a few menus and openvpn --help in all languages.

**Comment by zhovner** [comment]
Finished Ukrainian translation with missed strings https://github.com/selvanair/openvpn-gui/pull/7

**Comment by VasyaPRO** [comment]
This version is better: https://github.com/OpenVPN/openvpn-gui/pull/362

**Pull request closed without merging**
