### PR TITLE
Add instruction how to build using MSYS2

### PR DESCRIPTION
**Pull request by ffes**
Added an instruction how to build openvpn-gui using MSYS2

### CODE REVIEW

**Comment by mattock** [comment]
Could you mention that the instruction are for Arch Linux? Besides that looks good.

**Comment by ffes** [comment]
No, these **are** instruction to build using MSYS2. AFAIK MSYS2 has nothing to do with Arch Linux.

If you are not sure what MSYS2 is, look at their site (as mentioned in this PR): https://msys2.github.io/ which redirects to http://www.msys2.org/ since a (short?) while.

**Comment by chipitsine** [comment]
@ffes , I think we could interpet @mattock question as "almost nobody knows what msys2 is actually".
and some documentation would help here

I'm going to add msys2 build to app veyor soon (or you can). app veyor build script is documentation itself

there's question about windows builds: https://github.com/OpenVPN/openvpn-gui/pull/151 (see Selva Nair reply). building on windows differ in terms of string formatting. we should do something with that

**Comment by mattock** [comment]
@ffes: ah, I see, my bad. I did not realize pacman was in use outside of Arch Linux. I will merge this as-is, then.

**Pull request merged**
