### PR TITLE
Check group membership without needing connection to DC

### PR DESCRIPTION
**Pull request by selvanair**
(updated)
See also [Trac #810](https://community.openvpn.net/openvpn/ticket/810)

~Compare the SID of the user with member SIDs in the Administrators
group and ovpn_admin_group. This avoid issues on setups where the
DC may not be reachable and allows validating users logged in with
cached credentials.~
Authorize the user if

(i) admin groups are found in the process token
(ii) or the SID of the user is a member of the admin groups

The second check is needed to support adding the user to the
ovpn_admin_group when GUI is running, as such changes in group
membership will not be reflected in the token.

Same approach is used in the proposed patch (v2) for interactive service
http://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg13834.html

### CODE REVIEW

**Comment by selvanair** [comment]
Based on further discussions on Trac: #810, I plan to update the patch for interactive service to check nested membership as well. This PR will be updated to match the service at that point.

**Comment by selvanair** [comment]
I had forgotten to update this with the version that supports nested group membership -- force pushed the updated version. Matching patch for the service is already on the devel ML. A test executable with this version was tested by a couple of users (see [Trac #810](https://community.openvpn.net/openvpn/ticket/810))

**Comment by cron2** [comment]
feature-ACK, since we have this in openvpnserv now, GUI should match.  Code looks familiar though I have not done a full review

**Comment by selvanair** [comment]
We have a feature-ACK but no code ACK yet -- how far is the proposed 2.4.1?

**Comment by cron2** [comment]
Hi,

On Mon, Mar 06, 2017 at 03:14:09PM -0800, Selva Nair wrote:
> We have a feature-ACK but no code ACK yet -- how far is the proposed 2.4.1?

ACK, code changes look reasonable (both patches in this PR) :)

2.4.1 is supposed to happen "real soon now", but we haven't really decided
on a date.  Community meeting tomorrow, mayhaps.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by selvanair** [comment]
Thanks for the review. Merging.

**Pull request merged**
