### PR TITLE
Fix truncated text in some dialogs

### PR DESCRIPTION
**Pull request by selvanair**
Reported-by: @DanielBlackBeard

### CODE REVIEW

**Comment by selvanair** [comment]
@DanielBlackBeard This fixes the truncated Farsi text in the settings window that you had pointed out. Could you please give it a test run? CI build executables are here: https://github.com/selvanair/openvpn-gui/actions/runs/3610598565#artifacts

**Comment by selvanair** [comment]
Thanks for testing. Hope this fixes it:

general

**Comment by DanielBlackBeard** [comment]
Hello. thanks Again.
I am translating the parts that have not been translated, and I am considering the translation of other languages, and I am correcting the translation based on that, which in my opinion greatly improves the quality of the translation.
If it is possible, give me some time to finish this project so that a great translation can be made.
If the translation is finished, should I put it in the main branch or create a new branch?

**Comment by selvanair** [comment]
You can take as much time as you want and open your PR when ready --- or a series of PRs as you progress if that makes sense. Working locally on feature branches instead of the master makes that process easier. I would suggest to concentrate on untranslated text first and  then take up on improving existing translations as separate PRs.

Also. keep track of changes here as we frequently add new resource strings, and ensure that any PR submitted is rebased on top of the master branch here or at least is conflict-free.

Thanks for your interest.

**Comment by selvanair** [comment]
> Hello. thanks Again.
Taking that to mean the text truncation is fixed by the last commit. And, merging.

**Pull request merged**
