### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by MaxXor**
This PR completes the german translation and fixes some minor things.

### CODE REVIEW

**Comment by MaxXor** [comment]
Can anyone review?

**Comment by mattock** [comment]
@MaxXor sorry this slipped through. I asked @cron2 and @d12fk to review on IRC.

**Comment by mattock** [comment]
It seems we won't be getting any external review. I had a quick look and based on my 2 years of German studies from 25 years ago the PR looks reasonable 😄. In any case I'll merge this based on our lazy-ACK policy.

**Comment by cron2** [comment]
Hi,

On Tue, Jan 23, 2018 at 12:04:03PM +0000, Samuli Seppänen wrote:
> It seems we won't be getting any external review. I had a quick look and based on my 2 years of German studies from 25 years ago the PR looks reasonable ????. In any case I'll merge this based on our lazy-ACK policy. 

OK, sorry for slacking.

I agree to all changes but the *first* one - if that's really the
"change passphrase" dialog (as the comment suggests), calling it a
"Passwort" is confusing at best (because that would be a "password",
like in "username + password" while the passphrase is for the encrypted
key).


So *if* that's the passphrase, I'd change the caption to

 "OpenVPN - Public Key Passphrase ändern"

... and if not, the comment needs to be adjusted.

Neither should stop this from being merged, all the other changes are
a big improvement.

gert


-- 
now what should I write here...

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by mattock** [comment]
@cron2 excellent and thanks for the proper review! @MaxXor I merged this one already, but the fix proposed by @cron2  can be in a separate PR which, if merged by Thursday, will end up in OpenVPN 2.4.5 installers.

**Comment by MaxXor** [comment]
@mattock Thank you!
@cron2 I agree and will fix this in a separate PR. Thanks.

**Pull request merged**
