### PR TITLE
Highlight warning and error messages in status window

### PR DESCRIPTION
**Pull request by selvanair**
Change text colour of log lines flagged as Warning, Nonfatal error and Fatal error.
Colours defined by clr_warning and clr_error introduced in a previous patch are
used. Both of these are currently set as colour "red".

Signed-off-by: Selva Nair <selva.nair@gmail.com>

### CODE REVIEW

**Comment by cron2** [comment]
Hi,

On Thu, Sep 21, 2017 at 08:39:30PM -0700, Selva Nair wrote:
> Change text colour of log lines flagged as Warning, Nonfatal error and Fatal error.
> Colours defined by clr_warning and clr_error introduced in a previous patch are
> used. Both of these are currently set as colour "red".
> 
> Signed-off-by: Selva Nair <selva.nair@gmail.com>
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OpenVPN/openvpn-gui/pull/187

This is definitely a good thing.

Feature-ACK :-)

Code-wise, I'm wondering - where is text_clr reset to "normal" after
an error message?  Or is this automatic?  (I see a "if it's not 0, 
send EM_SETCHARFORMAT" but no "reset to 0 if we had an error").

Also, I do not see where OnLogLine() is called ("callback'ed"), so I'm
not sure if we can rely on "line" being writeable.  But since you've
commented it explicitely, I think I just believe this works :-)

So, code-ACK if this has been taken care of.

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by selvanair** [comment]
Thanks for the review.. 

For those who are wondering how this looks -- [here](https://imagebin.ca/v/3bHOlOEhPFkP) is a screenshot

>Code-wise, I'm wondering - where is text_clr reset to "normal" after
>an error message?  Or is this automatic?  (I see a "if it's not 0,
>send EM_SETCHARFORMAT" but no "reset to 0 if we had an error").

EM_SETCHARFORMAT is sent with flag = SCF_SELECTION which means it applies to the current selection if any (we have none) or to the insertion point until that point changes. We always send a new line at the end which changes the insertion point and that implicitly resets the colour back to default. This could be made more explicit, though..

>Also, I do not see where OnLogLine() is called ("callback'ed"), so I'm
>not sure if we can rely on "line" being writeable.  But since you've
>commented it explicitely, I think I just believe this works :-)

The callback is referred to as `rtmsg_handler[logline]()` in manage.c. On return, the caller moves on to the next line so its safe. Yet I would like to avoid modifying line here but a strdup of every log line looked like an overkill..

Just realized we can use message-flag as the length and then memchr instead of strchr to search for the character. I'll push a commit to do that.

**Comment by cron2** [comment]
Hi,

On Fri, Sep 22, 2017 at 03:44:25PM +0000, Selva Nair wrote:
> For those who are wondering how this looks -- [here](https://imagebin.ca/v/3bHOlOEhPFkP) is a screenshot

I used my imagination, and "visually marking error/warnings in lots of
informative text" sounded good enough :-)

> >Code-wise, I'm wondering - where is text_clr reset to "normal" after
> >an error message?  Or is this automatic?  (I see a "if it's not 0,
> >send EM_SETCHARFORMAT" but no "reset to 0 if we had an error").
> 
> EM_SETCHARFORMAT is sent with flag = SCF_SELECTION which means
> it applies to the current selection if any (we have none) or to the
> insertion point until that point changes. We always send a new line
> at the end which changes the insertion point and that implicitly
> resets the colour back to default. This could be made more explicit,
> though..

Thanks for the explanation.  Good enough :-)

> >Also, I do not see where OnLogLine() is called ("callback'ed"), so I'm
> >not sure if we can rely on "line" being writeable.  But since you've
> >commented it explicitely, I think I just believe this works :-)
> 
> The callback is referred to as `rtmsg_handler[logline]()` in manage.c. On return, the caller moves on to the next line so its safe. Yet I would like to avoid modifying line here but a strdup of every log line looked like an overkill..
> 
> Just realized we can use message-flag as the length and then memchr instead of strchr to search for the character. I'll push a commit to do that.

This would be nicer, neither strdup()'ing nor modifying the caller's 
string.  Thanks.

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by selvanair** [comment]
>This would be nicer, neither strdup()'ing nor modifying the caller's
>string.  Thanks.
> gert

Pushed a commit to do so. (commit 44aa5ac5b445195c996dbeaa91bd40bfa0f08a4c)

**Comment by cron2** [comment]
Hi,

On Sat, Sep 23, 2017 at 12:41:21AM +0000, Selva Nair wrote:
> >This would be nicer, neither strdup()'ing nor modifying the caller's
> >string.  Thanks.
> > gert
> 
> Pushed a commit to do so. (commit 44aa5ac5b445195c996dbeaa91bd40bfa0f08a4c)

Looks good to me.  ACK.

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Pull request merged**
