### PR TITLE
Translate missing Dutch strings and minor changes

### PR DESCRIPTION
**Pull request by EagleErwin**

### CODE REVIEW

**Comment by EagleErwin** [comment]
I am still struggling with the translation of Preconnect/Postconnect/Connect Script.
I'm happy to receive suggestions for that.

**Comment by selvanair** [comment]
@mattock: do we have anyone who could review this?

**Comment by mattock** [comment]
Yes, I sent email syzzer.

**Comment by syzzer** [comment]
Looks good to me.  Some useful additions, and changes to improve consistency.

**Comment by selvanair** [comment]
Merging based on syzzer's review

**Pull request merged**
