### PR TITLE
Add title and TravisCI badge to README.rst

### PR DESCRIPTION
**Pull request by Chocobo1**

### CODE REVIEW

**Comment by chipitsine** [comment]
travis-ci performs very few checks, actually "cppcheck" and "compile check"
no unit testing, no integration testing, no fuzz testing, no functional testing...

I'm afraid people will think "uh-huh, there's travis-ci badge, project is well tested"..

**Comment by mattock** [comment]
The badge just says "build passing":

* https://github.com/Chocobo1/openvpn-gui/blob/badge/README.rst

I think it would be useful to have that info on the front page.

**Comment by chipitsine** [comment]
I know how does the badge look like ))

**Comment by mattock** [comment]
@chipitsine : are you opposed to having the badge, then :smile: ?

**Comment by chipitsine** [comment]
no, I'm not opposite.

however, with current test coverage I think it is almost useless.

**Comment by mattock** [comment]
As the badge does not make any false promises, I'll merge this then. We should definitely increase test coverage, but that's for another topic/pull request.

**Pull request merged**
