### PR TITLE
Update Polish translation in openvpn-gui-res-pl.rc

### PR DESCRIPTION
**Pull request by kauczu**
- the style of the translation has been slightly improved,
- untranslated fields has been translated

### CODE REVIEW

**Comment by thebodzio** [comment]
Przepraszam! Zauważyłem, że w kolejce jest już update do polskiego tłumaczenia, jak już zrobiłem pull requesta. Byłeś pierwszy w kolejce, więc wycofuję swojego. Jeśli chcesz możesz zerknąć na moją wersję: https://github.com/thebodzio/openvpn-gui/blob/595d01bf5b4126cd0571195867c6741f33b5af8a/res/openvpn-gui-res-pl.rc

**Comment by selvanair** [comment]
@thebodzio We could get this merged if you can provide a review. Thanks.

**Comment by thebodzio** [comment]
I think this is a solid translation. I wouldn't translate everything the very same way, but this is a big improvement over the current state of affairs.

For the sake of clarity, I wrote to @kauczu, quote: _I'm sorry! I only noticed your Polish translation after I did my pull request. You were first in that regard, so I'm closing mine. If you'd like, you are welcome to take a look at my translation: https://github.com/thebodzio/openvpn-gui/blob/595d01bf5b4126cd0571195867c6741f33b5af8a/res/openvpn-gui-res-pl.rc_

**Comment by selvanair** [comment]
> I think this is a solid translation. I wouldn't translate everything the very same way, but this is a big improvement over the current state of affairs.

Thanks. I suppose I can take that as an ACK / Approval

> 
> For the sake of clarity, I wrote to @kauczu, quote: _I'm sorry! I only noticed your Polish translation after I did my pull request. You were first in that regard, so I'm closing mine. If you'd like, you are welcome to take a look at my translation: https://github.com/thebodzio/openvpn-gui/blob/595d01bf5b4126cd0571195867c6741f33b5af8a/res/openvpn-gui-res-pl.rc_

Google translate helped me with that.. lol.

Anyway, will wait  a couple of days in case @kauczu wants to change anything based on your branch.

**Comment by thebodzio** [comment]
Thank you, sir! 👍 😄

**Comment by kauczu** [comment]
I do not know what to say :)

@thebodzio I have the same thoughts about your translation. Very good job! 
I have analyzed it but I would translate it slightly differently.

@selvanair I will be happy if my translation will be merged. I would also not mind if translation of @thebodzio will be used. Regardless of which translation will be merged, OpenVPN will have a better Polish user interface :)

**Comment by thebodzio** [comment]
I'm happy to see this merged 😄. Thank you, @selvanair! 👍 

@kauczu It doesn't really matter whose translation is used. I'm just glad to see Polish localization improved 😄. We all know it was waaay overdue 😉.

All the best!

**Pull request merged**
