### PR TITLE
Use a custom tooltip window for the tray icon

### PR DESCRIPTION
**Pull request by selvanair**
Built-in tray notification icon has a tip text length limit of 128 characters which is often limited for showing the connected profile name, connected since time and IP addresses. If the profile name is long the IP numbers could get truncated.

Fix by using a custom tooltip window and display it when mouse hovers over the icon. As the status bar need not be at the bottom of the screen (could be at right, left or top as well), the location of the window is chosen based on the mouse co-ordinates that trigger the hover event.

In case of errors while setting up the tooltip window, fall back to the current behaviour.

If the message is too long to include time and IP, truncate the profile name part of the message.

Fixes issue #666

Edit: force pushed after fixing some typos in commit message and buggy text truncation logic.

old

Screenshot from 2024-02-10 17-11-34

new

Screenshot from 2024-02-10 17-14-56

### CODE REVIEW

**Comment by cron2** [comment]
I like the idea, but do not feel qualified today to ACK or NAK the code. @lstipakov something for you?

**Comment by lstipakov** [comment]
Hi,

On Windows 11 there are two issues;

 - When there is no connection, there is no tooltip at all. Currently we display `OpenVPN GUI` there.
 - When there is active connection, tooltip is displayed on top left. Currently we display it next to the tray.
Näyttökuva 2024-02-12 110020

Näyttökuva 2024-02-12 110139

**Comment by selvanair** [comment]
linking to my comment https://github.com/OpenVPN/openvpn-gui/issues/666#issuecomment-1938927344

**Comment by selvanair** [comment]
Force pushed with changes:
 - For some reason wParam does not contain the position in NIN_POPUOPEN message. Fixed by using GetCrursorPos() to determine the mouse location. 
 - Also fixed the empty message bug.

**Comment by selvanair** [comment]
(Moving this to the right place)
Pushed two commits:
(i) Remove title and prepend it to the message
(ii) Position the message at a fixed distance above the icon instead of tracking the mouse position
(figured how to do this :)

On Win11 the tip window should probably have rounded corners, but will leave it at that.

**Review by lstipakov — APPROVED** [review]
Tested on Windows 11. Both tooltip and code look good.

**Pull request merged**
