### PR TITLE
Expand - Persian(farsi) language translation

### PR DESCRIPTION
**Pull request by jav6**
Translate OpenVPN GUI to farsi language until --> options – Resources
I expand translation  and add to main project (master branch) --> (sometimes)

### CODE REVIEW

**Comment by selvanair** [comment]
Please resolve conflicts by rebasing to the current master.

**Comment by jav6** [comment]
@selvanair -- I think the problem was solved

**Comment by selvanair** [comment]
@jav6 This wont work. You have to rebase to upstream/master (not merge) and then resolve any conflicts. At that point your branch will correctly show up as exactly 1 commit (the new translations) ahead of master here.

**Comment by jav6** [comment]
I think it was finally solved

**Comment by selvanair** [comment]
> @selvanair I think it was finally solved - if it is have problem say to me
> for rebase --> my method (if it is not good -- please say to me) : 1.git remote add upstream https://openvpn... 2.git fetch upstream 3.git merge upstream/master

No, its not good. You have to add a single commit to the current master. There are many ways to fix it, but the following is the easiest for me to describe. In your local repo do the following two steps:

1. `git checkout e4fba06 -b farsi`
(this will check out upstream master into a new branch named farsi)

2. `git cherry-pick ef7174b5`
(this picks the new commit and adds it to the above branch)

Ideally also do, `git commit --amend -s` to sign-off the commit.

That should complete without error. If so, push that new branch "farsi" to your github repo and issue a new PR from it.

To see how the result will look like, see the branch named farsi I have created using the above steps: https://github.com/selvanair/openvpn-gui/tree/farsi

**Comment by jav6** [comment]
@selvanair Thanks for your help - I created new pull request --> #393

**Comment by selvanair** [comment]
Closing this as superseded by #393

**Pull request closed without merging**
