### PR TITLE
Add Persian language

### PR DESCRIPTION
**Pull request by jav6**
I added Persian language to app - with translate file content (*-en.rc) to persian and add -> (*-fa.rc) file in -> res - folder

### CODE REVIEW

**Comment by selvanair** [comment]
Thanks for the PR. This is a nice addition.

For the new resources to get compiled in, you have to add an include line in res/openvpn-gui-res.h. Like this:
#include openvpn-gui-res-fa.rc
And add "LANG_FARSI,  1200" to the translation file info in the same file around line 96.

mingw resource compiler doesn't  recognize LANG_PERSIAN, can you use LANG_FARSI instead?

Some prompts like password end with a " :D". Is that deliberate?

**Comment by jav6** [comment]
Thanks for responding and help me 
I add :
"#include openvpn-gui-res-fa.rc" and "LANG_FARSI, 1200" --to--> res/openvpn-gui-res.h.*
Change:
 text(or...) - 'LANG_PERSIAN'--to-->'LANG_FARSI'
and
I remove ' :D ' from -> Some prompts
(I added it for - sort - code):

**Comment by selvanair** [comment]
Thanks for the changes.
Any native speakers around to give this a quick review? Also comment on whether users would expect dialog boxes to be mirrored for RTL script, i.e., right aligned (not done here), is the use of abbreviations like SU (start up?), Pre (?) are appropriate etc..

**Comment by jav6** [comment]
How can i do rtl align box and text (or if - just text be rtl - is better)??? -> how can i do (righ to left) text?
--------------------------------------------------------------------
This abbreviations (Pre or SU and ...) not essential - so - i remove it

**Comment by jav6** [comment]
If no have idea for right to left(app -> text) in farsi language ---and--- no problem in my (edit of)code - please merge -> my pull request - thank you

**Comment by selvanair** [comment]
I would have preferred to have an independent review by someone who knows the language.
@mattock do we have anyone who can give this a quick look over? Or merge as is? -- fwiw, google translate doesn't show anything offending in the translation.
@jav6 too many piece-meal commits in here -- I can squash them into one during merge unless you want to clean it up and force-push.

**Comment by jav6** [comment]
I don’t want clean it up and force-push --- do squash it

**Comment by mattock** [comment]
@selvanair I'm not aware of anyone (else) in the community speaking Farsi. Let's merge this as-is.

**Comment by selvanair** [comment]
@jav6 Thanks for the contribution. Merged. Looking forward to a PR extending this to yet untranslated text.

**Pull request merged**
