### PR TITLE
Some small bug fixes

### PR DESCRIPTION
**Pull request by selvanair**
Broken into 4 commits: only the 3rd one fixes a bug that is easy to reproduce (try an empty password with static challenge).
@soarqin could you please check it doesn't break the rest of the static challenge code?

### CODE REVIEW

**Comment by soarqin** [comment]
This patch works fine. It was my mistake that not to handle empty input.

**Comment by mattock** [comment]
These fixes look very reasonable. I'll ask if someone on #openvpn-devel could do a proper code review and if that fails, I think we should merge these with lazy-ACK.

**Comment by ffes** [comment]
As requested by @mattock I took a look at the changes. Disclaimer in advance. I have little to no experience with the code of openvpn-gui. Only just started to contribute, just translations so far.

If I understand correctly, @soarqin already gave his approval on the base64 code. I haven't got a clue how to test the other code, but it looks good to me.

I am not a fan of the `== FALSE` check, but that is really personally and arbitrarily. On the other hand, in `misc.c` you use `if (!Base64Encode())`.

**Comment by selvanair** [comment]
Thanks for the comments. Sometimes == FALSE is easier to read, but not in this case.  Will change it.

**Comment by mattock** [comment]
@ffes: Thanks for the review! We're quite low on manpower on the Windows front, so your help is most welcome!

@selvanair: so now we have code review from @ffes, and @soarqin tested that the [Handle empty strings in Base64Encode](https://github.com/OpenVPN/openvpn-gui/pull/33/commits/875d9f94578d0c299a04efe317e4d0e89f59c2de) patch does not break anything. Enough testing and review for a merge in your opinion?

**Comment by selvanair** [comment]
@samuli This is pretty harmless and we have a review + test. OK to merge, I think.

**Comment by ffes** [comment]
@mattock I understand your request, but I can't promise much.

Some background. I am a Windows developer and sysadm. I work at a company where we use openvpn on our pfSense firewall. We have ~20 Windows clients. My main interest is the user experience for me and my users, thus openvpn-gui. I am not the "security" guy.

**Comment by mattock** [comment]
@selvanair: Ok, I'll merge this.
@ffes: Ok - we have security guys on the OpenVPN side, so that part is covered pretty well already.

**Pull request merged**
