### PR TITLE
Read errors from the service pipe and handle fatal ones

### PR DESCRIPTION
**Pull request by selvanair**
To test, try to trigger an option error or an auth error using, say, config in user profile 
as a limited user, not member of ovpn_admin_group. Interactive service must be running.
This is against the current master, may not cleanly apply on top of PR#26

### CODE REVIEW

**Comment by selvanair** [comment]
It would be useful to hear whether anyone finds this useful at all. Or is it too much code with little utility for most folks?

**Comment by cron2** [comment]
Hi,

On Tue, Mar 22, 2016 at 08:31:27PM -0700, Selva Nair wrote:
> It would be useful to hear whether anyone finds this useful at all. Or is it too much code with little utility for most folks?

I find it totally useful, but was too much distracted by other stuff to
review or test.  So "feature-ACK" from me.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment]
Any chance of getting a code review from the OpenVPN side, or do we have to resort to lazy-ACK to get this in?

**Comment by mattock** [comment]
@selvanair : I think we've clearly reached the point of lazy-ACK. Anything you'd like to change in this PR, or shall I merge it as-is?

**Comment by selvanair** [comment]
@mattock: Just to be sure I've rebased the patch to master.  No other changes from my side.

**Comment by mattock** [comment]
Ok, I'll merge this. Thanks!

**Pull request merged**
