### PR TITLE
Warn on auth failure

### PR DESCRIPTION
**Pull request by selvanair**
When authentication or private key password is re-prompted due to wrong credentials, show a warning text (colored red) that username or password entered was incorrect.

Additional commits:
- keep track of auth failure and key password failure separately: needed to show appropriate warning text on wrong password
- Russian localization from @chipitsine 
- Fix text clipping in Private key password dialog
- Fix overlapping buttons in Korean user-auth dialog

### CODE REVIEW

**Comment by ValdikSS** [comment]
@zhovner please translate to Ukrainian too. Just these two lines:
`IDS_NFO_AUTH_PASS_RETRY "Неправильное имя пользователя или пароль"`
`IDS_NFO_KEY_PASS_RETRY  "Неправильный пароль"`

**Comment by zhovner** [comment]
IDS_NFO_AUTH_PASS_RETRY "Невірне ім'я користувача або пароль"
IDS_NFO_AUTH_PASS_RETRY "Невірний пароль"

**Comment by ValdikSS** [comment]
@selvanair can you please include @zhovner's Ukrainian translation into this pull request?
@chipitsine please make sure Ukrainian text is aligned properly.

**Comment by chipitsine** [comment]
@ValdikSS , why not to check yourself ?
just follow to App Veyor https://ci.appveyor.com/project/mattock/openvpn-gui/build/cygwin-55
PR builds are there as well

**Comment by chipitsine** [comment]
can we merge it ?

**Comment by selvanair** [comment]
It would be nice if someone could review the code and give an ACK -- not just that it works, but that a code review. If that's not forthcoming we'll merge it eventually.

**Comment by chipitsine** [comment]
can we merge if before 2.4.3 ?

**Comment by mattock** [comment]
@chipitsine even if this fails to make it to the initial 2.4.3 installers we can release new Windows installers easily.

**Comment by chipitsine** [comment]
do you mean newer 2.4.3 in place of older 2.4.3 ?

**Comment by mattock** [comment]
The new installer would contain OpenVPN 2.4.3 but other things (easy-rsa, openvpn-gui, tap-windows6 and NSI installer) might have been updated. We do these "Windows installer only" releases fairly often.

**Comment by cron2** [comment]
Hi,

On Tue, Jun 20, 2017 at 04:04:21AM -0700, Ilya Shipitsin wrote:
> can we merge if before 2.4.3 ?

It won't make 2.4.3, sorry.  We're already building bundles so the release
can happen tomorrow, 12:00 UTC+2.

I have it somewhere on my TODO list, and I hope I'm able to do more regular
review/release work in the next months (not "one week of flurry and then
two months nothing" like earlier this year)...

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment]
I won't be able to bundle easy-rsa 2.3.0 due to https://github.com/OpenVPN/openvpn-build/pull/93, so we should probably do a separate installer release soon after the release.

**Comment by cron2** [comment]
Hi,

On Thu, Jun 08, 2017 at 09:14:19AM -0700, Selva Nair wrote:
> When authentication or private key password is re-prompted due to wrong credentials, show a warning text (colored red) that username or password entered was incorrect.
> 
> Additional commits:
> - keep track of auth failure and key password failure separately: needed to show appropriate warning text on wrong password
> - Russian localization from @chipitsine 
> - Fix text clipping in Private key password dialog
> - Fix overlapping buttons in Korean user-auth dialog
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OpenVPN/openvpn-gui/pull/171

ACK on the code changes (and the feature).

Didn't review *all* the .rc files to see if something changed in
suprising ways...

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Pull request merged**
