### PR TITLE
cppcheck cleanup:

### PR DESCRIPTION
**Pull request by chipitsine**
[openvpn_config.c:194]: (style) The function 'ConfigFileOptionExist' is never used.
[localization.c:299]: (style) The function 'LocalizedDialogBox' is never used.
[main.c:549]: (style) The function 'PrintErrorDebug' is never used.
[main.c:583]: (style) The function 'init_security_attributes_allow_all' is never used.
[misc.c:180]: (style) The function 'wcseq' is never used.

### CODE REVIEW

**Comment by mattock** [comment]
Do you use openvpn-build to build openvpn-gui? I need to verify that this does not break the official builds.

**Comment by chipitsine** [comment]
I built openvpn-gui separately, using the same thing as openvpn-build. It compiled ok, and it works.
openvpn-build script uses openvpn-gui tarball at http://build.openvpn.net, I've no idea how to put tarball there.

**Comment by mattock** [comment]
If you put the tarball to a webserver, I can do a test build using it and then merge the pull request. Alternatively you can email the tarball to me.

**Comment by chipitsine** [comment]
you can clone https://github.com/chipitsine/openvpn-gui and make a tarball if you wish to.

**Comment by mattock** [comment]
Building the patched version with openvpn-build worked. Merging.

**Pull request merged**
