### PR TITLE
Fix exit handling while in modal loops

### PR DESCRIPTION
**Pull request by selvanair**
**How to test:**
Using the current GUI and interactive service, start a connection
that needs user-auth. While that dialog is open press the exit button 
from the tray menu. The GUI will exit after waiting for a few seconds but 
the openvpn.exe process will be left behind (will have to be killed manually 
before a new connection can be made). This patch should fix it.

**Commit message:**
PostThreadMessage used to trigger exit event gets lost while
in modal loops such as auth dialog. Replace it by PostMessage
and handle it in the status window callback.

Fixes openvpn processes left behind if exit is pressed while
user-auth dialog is active.

Signed-off-by: Selva Nair <selva.nair@gmail.com>

### CODE REVIEW

**Comment by leobasilio** [comment]
The issue is real, and the patch does work as intended. There's just this compilation warning:

>../openvpn-gui/openvpn.c:1165:17: warning: passing argument 1 of 'PostMessageW' makes pointer from integer without a cast [-Wint-conversion]
>     PostMessage(o.conn[config].threadId, WM_OVPN_SUSPEND, 0, 0);

**Comment by selvanair** [comment]
On Sun, May 22, 2016 at 9:23 PM, Leonardo Basilio <notifications@github.com>
wrote:

> The issue is real, and the patch does work as intended. There's just this
> compilation warning:
>
> ../openvpn-gui/openvpn.c:1165:17: warning: passing argument 1 of
> 'PostMessageW' makes pointer from integer without a cast [-Wint-conversion]
> PostMessage(o.conn[config].threadId, WM_OVPN_SUSPEND, 0, 0);
>
>
Thanks. That is a bug -- forgot to change the threadId to window handle in
SuspendOpenVPN. It may not show up in normal use as suspend is probably
never used anymore. Will fix and push a new version.

**Comment by selvanair** [comment]
Pushed a fixup.

**Comment by mattock** [comment]
@leobasilio : compile problem gone?

**Comment by leobasilio** [comment]
Yes. It's gone.

**Comment by chipitsine** [comment]
we can add -Werror to gcc/Makefile

**Comment by selvanair** [comment]
@leobasilio has confirmed the bug and tested the patch. What about the code itself -- is it good to be merged?

**Comment by selvanair** [comment]
@mattock : this bug fix has been tested by leobasilio, so may be merge with a lazy ACK?

**Comment by mattock** [comment]
@selvanair: :+1: merging.

**Pull request merged**
