### PR TITLE
Support pkcs11-id-management

### PR DESCRIPTION
**Pull request by selvanair**
Features
- shows a list of pkcs11 certificates for user to select from
- double click on any entry to see more details of the certificate
- suggest to insert a token if no certificates found
- retry button to reload certificate list

Requires --pkcs11-id-management in the config file.

Issue #158

### CODE REVIEW

**Comment by lstipakov** [comment]
I am not too much into pkcs11, is there any way I could test this?

Also shouldn't we update all language resources with the new dialog?

**Comment by selvanair** [comment]
> I am not too much into pkcs11, is there any way I could test this?
> 
> Also shouldn't we update all language resources with the new dialog?

I thought of getting  some feedback before copying resources -- in case the UI needs change/improvement. 

Once could use softhsm to make a software token and test, but I have never tried this on Windows. The following is based on the steps I follow on Linux. Softhsm2 and pkcs11-tool (from opensc) are available for windows, so should work there as well

```
pkcs11-tool.exe --module path-to-lib\softhsm2-x64.dll --init-token --label SoftToken  
```

load existing client.key and client.cert files to the token

```
pkcs11-tool.exe --module path-to-lib\softhsm2-x64.dll --login -w client.key --type privkey --id 1
pkcs11-tool.exe --module path-to-lib\softhsm2-x64.dll --login -w client.cert --type cert  --id 1 
```
use same id for matching key and cert to match. Add more key-pairs each pair with a unique id.

Test as
`openvpn--show-pkcs11-ids path-to-lib\softhsm2-x64.dll`

Add to openvpn config
`pkcs11-providers path-to-lib\softhsm2-x64.dll`

**Comment by selvanair** [comment]
Alternatively, the following appears to work:

Install only softhsm2 [note]. Then unzip the following to its `var\softhsm2\tokens\`  folder.

https://drive.google.com/file/d/1-DJRGXEyZBhEgGC8vba9oWI9-Jfqcy6D/view?usp=sharing

This zip file contains a "soft token" I created with sample certificates and keys in OpenVPN repo.  The so and user PINs are both set to 1234.

`openvpn --show-pkcs11-ids <softhsm-path>\lib\softhsm2-x64.dll` should then display certificates available.

But, to connect using this, the server has to obviously accept keys signed by the sample ca.

[note]
If using the portable zip version of softhsm2, set SOFTHSM2_CONF to `<softhsm-path>\etc\softhsm2.conf` and edit that file to point directories.tokendir to `<softhsm-path>\var\softhsm2\tokens`). No other setup needed.

**Comment by lstipakov** [comment]
Sorry for the delay. I followed @selvanair's instructions and got dialog with certificates in GUI. However, when I selected certificate, openvpn process crashed.
xkey_bug

Not sure if crash is related to this change, though.

**Comment by selvanair** [comment]
As the crash is in openvpn.exe and seems to shwo the sign() callback address in xkey_provider is 0xFFFFFFFFFF, this has to be unrelated. But this should not happen -- what version of openvpn.exe is this?
Can you try with pkcs11-id-management replaced by 'pkcs11-id <ID>' in the config file where <ID> is the one reported by `openvpn.exe --show-pkcs11-ids <provider-dll>` ? Or copy the ID from the log file. If that shows the same crash, we know its unrelated to the GUI.

**Comment by lstipakov** [comment]
Yes I got the same crash. I use locally-built openvpn master.

**Comment by selvanair** [comment]
I will try to reproduce -- did we break xkey-provider + pkcs11-helper !?

**Comment by selvanair** [comment]
@lstipakov  I'm unable to reproduce this using mingw built master + OpenSSL 3.0.1. The OpenSSL lib for Windows I use is an slightly old build  though (From Dec 2021). I suppose plain --cert and --key options do work with your build. Does cryptoapicert work? That also uses xkey-provider and the sign_op function pointer. 

The value of 0xFFFFFFFF you see in debugger  is probably -1, but  that's bizarre as its a function pointer passed through OpenSSL params (as octet pointer).

**Comment by lstipakov** [comment]
@selvanair I also managed to reproduce it with GHa binaries from master (https://github.com/OpenVPN/openvpn/actions/runs/2579097466).

**Comment by lstipakov** [comment]
(I'll be on vacation till 17.7, I can have a look into xkey-provider thing if we haven't figure it out by then)

**Comment by selvanair** [comment]
Patch for sent to the devel list should hopefully fix it.

**Comment by lstipakov** [comment]
I finally managed to test it against the latest master, including abovementioned patch, works as expected!

**Review by lstipakov — APPROVED** [review]

**Pull request merged**
